urls = ["https://www.linkedin.com/jobs/view/4033227418/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=YSvcqzqpgqvBYQ78c69z4A%3D%3D&trk=flagship3_search_srp_jobs",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",
"https://www.linkedin.com/jobs/view/4034386579/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3D",

"https://www.linkedin.com/jobs/view/40343865739/?eBP=NOT_ELIGIBLE_FOR_CHARGING&refId=TiUGGkPYEMf53AKq8mB7Ig%3D%3D&trackingId=wsesYfAUsIPBEDDtrePbwg%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BS32rVvZETtiCKljEmQfPMA%3D%3D&lici=wsesYfAUsIPBEDDtrePbwg%3D%3Da"
]
uniq_job = []
uniq_id = set()
for i in urls:
    number = i.split("view/")[1].split("/")[0]
    if number not in uniq_id:
        uniq_id.add(number)
        uniq_job.append(i)

with open("Urls.txt","w") as file:
    for i in uniq_job:
        file.write(i + "\n")
print("Program Terminate.............................................u")